[project]
name = "tracker-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "PEI-YING-1122", email = "milkmillk1256@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
tracker-tool = "tracker_tool:main"

[build-system]
requires = ["uv_build>=0.9.28,<0.10.0"]
build-backend = "uv_build"
