"""Write the third-party attributions of the Qt modules shipped in the GUI bundle.

Reads qt_attribution.json and the license files they reference from the
official Qt 6.11.2 source archives (qtbase, qtsvg, qtimageformats), and writes
one text file with every component's name, version, license, copyright and
full license text.

Usage (from the repository root):

    python packaging/qt_attributions.py <dir with *-everywhere-src-6.11.2.tar.xz>

Components that are only built for other platforms, or for Qt modules that
are not in the bundle, are left out (see EXCLUDED_PATHS). Everything else is
kept, so the list may include components that the Windows binaries do not
contain.
"""

import argparse
import json
import posixpath
import tarfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
QT_VERSION = "6.11.2"
MODULES = ("qtbase", "qtsvg", "qtimageformats")
OUTPUT = ROOT / "packaging" / "licenses" / f"Qt-{QT_VERSION}-third-party-attributions.txt"

# Path prefixes (inside a module) of attributions that do not apply to the
# Windows bundle: other platforms, build tooling, tests, and Qt modules that
# are not shipped (Qt D-Bus, Qt SQL).
EXCLUDED_PATHS = (
    "cmake/",
    "util/",
    "src/testlib/",
    "src/testinternal/",
    "src/dbus/",
    "src/3rdparty/android/",
    "src/3rdparty/gradle/",
    "src/3rdparty/wasm/",
    "src/3rdparty/wayland/",
    "src/3rdparty/xcb/",
    "src/3rdparty/sqlite/",
    "src/3rdparty/forkfd/",
    "src/plugins/platforms/cocoa/",
)


def read_module(archive: Path) -> list[dict]:
    entries = []
    with tarfile.open(archive) as tar:
        members = {member.name: member for member in tar.getmembers()}
        for name in sorted(members):
            if posixpath.basename(name) != "qt_attribution.json":
                continue
            top, relative = name.split("/", 1)
            if relative.startswith(EXCLUDED_PATHS):
                continue
            # Some Qt attribution files have raw tabs inside strings.
            data = json.loads(
                tar.extractfile(members[name]).read().decode("utf-8"), strict=False
            )
            for item in data if isinstance(data, list) else [data]:
                item["_module"] = top.split("-everywhere")[0]
                item["_path"] = posixpath.dirname(relative)
                item["_license_texts"] = [
                    (file_name, _read_text(tar, members, posixpath.dirname(name), file_name))
                    for file_name in _license_files(item)
                ]
                entries.append(item)
    return entries


def _license_files(item: dict) -> list[str]:
    files = item.get("LicenseFiles") or item.get("LicenseFile") or []
    return [files] if isinstance(files, str) else list(files)


def _read_text(tar, members, base: str, file_name: str) -> str:
    path = posixpath.normpath(posixpath.join(base, file_name))
    member = members.get(path)
    if member is None:
        raise SystemExit(f"license file not found in archive: {path}")
    return tar.extractfile(member).read().decode("utf-8", errors="replace").strip()


def _copyright(item: dict) -> str:
    value = item.get("Copyright", "")
    return "\n".join(value) if isinstance(value, list) else value


def render(entries: list[dict]) -> str:
    lines = [
        f"Third-party components in Qt {QT_VERSION} (Qt Base, Qt SVG, Qt Image Formats)",
        "",
        "Generated by packaging/qt_attributions.py from the qt_attribution.json files",
        f"in the official Qt {QT_VERSION} source archives. Components for other platforms",
        "and for Qt modules not in this bundle are left out. The list may include",
        "components that the Windows binaries do not contain.",
        "",
    ]
    for item in entries:
        lines += [
            "=" * 78,
            f"{item.get('Name', item.get('Id', '?'))}"
            + (f" {item['Version']}" if item.get("Version") else ""),
            f"Qt module : {item['_module']} ({item['_path']})",
            f"License   : {item.get('License', '')} ({item.get('LicenseId', '')})",
        ]
        if item.get("DownloadLocation"):
            lines.append(f"Source    : {item['DownloadLocation']}")
        if _copyright(item):
            lines += ["", _copyright(item)]
        for file_name, text in item["_license_texts"]:
            lines += ["", f"--- {posixpath.basename(file_name)} ---", text]
        lines.append("")
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("sources", type=Path)
    args = parser.parse_args(argv)

    entries = []
    for module in MODULES:
        entries += read_module(args.sources / f"{module}-everywhere-src-{QT_VERSION}.tar.xz")
    OUTPUT.write_text(render(entries), encoding="utf-8", newline="\n")
    print(f"{len(entries)} components -> {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
